#!/usr/bin/python

import ConfigParser
import imaplib
import re
import subprocess
import time
import logging
from cnotmuch import notmuch

mid_regexp = re.compile('message-id: +\<(.*)\>', re.IGNORECASE)
ret_regexp = re.compile('([0-9]+) +.*')

# The `find_message' routine will throw an exception if the database
# is modified in another thread, so we have to retry in that case.
def mid_exists(nm, mid):
    global debug

    exists = False
    attempted = False
    while not attempted:
        try:
            exists = nm.find_message(mid)
            attempted = True
        except NotmuchError:
            logging.debug('Exception during find_message')
            pass
    return exists

def poll_server(host, user, password, extension):
    global nm

    srv = imaplib.IMAP4_SSL(host)
    srv.login(user, password)
    typ, msgnums = srv.select()
    bottom = '1'
    for top in msgnums:
        logging.debug('Checking the range %s - %s.' % (bottom, top))
        typ, data = srv.fetch('%s:%s' % (bottom, top), '(BODY.PEEK[HEADER.FIELDS (MESSAGE-ID)])')
        for mid_or_str in data:
            if type(mid_or_str) == tuple:
                (ret, mid) = mid_or_str
                mid_match = mid_regexp.match(mid)
                if mid_match:
                    mid = mid_match.group(1)
                    if not mid_exists(nm, mid):
                        logging.info('New: %s' % mid)
                        ret_match = ret_regexp.match(ret)
                        if ret_match:
                            num = ret_match.group(1)
                            typ, data = srv.fetch(num, '(RFC822)')
                            procmail(data[0][1], extension)
                        else:
                            logging.debug('Return code regexp did not match (%s).' % ret)
                else:
                    logging.debug('Message ID regexp did not match (%s).' % mid)
        bottom = top
    srv.close()
    srv.logout()

def delete_old(host, user, password, delay):

    # `delay' is in days.
    then = time.time() - (delay * 24 * 60 * 60)
    thenstr = time.strftime('%d-%b-%Y', time.gmtime(then))

    srv = imaplib.IMAP4_SSL(host)
    srv.login(user, password)
    typ, msgnums = srv.select()
    typ, data = srv.search(None, '(BEFORE %s)' % thenstr)
    if data[0] != "":
        logging.info('Deleting %s' % data[0])
        srv.store(','.join(data[0].split()), '+FLAGS', '\\Deleted')
    srv.close()
    srv.logout()

def procmail(message, extension):
    args = ['procmail']
    if extension != '':
        args += ['-a', extension]

    p = subprocess.Popen(args, stdin = subprocess.PIPE).stdin
    # Remove DOS line endings.
    # Is this completely safe?
    p.write(message.replace("\x0d\x0a", "\x0a"))
    p.close()


def main():
    global nm
    config = ConfigParser.ConfigParser()
    config.read('notsync.cfg')
    log_level = logging.WARN

    if config.has_option('general', 'verbose') and \
            config.getboolean('general', 'verbose'):
       log_level = logging.INFO

    if config.has_option('general', 'debug') and \
            config.getboolean('general', 'debug'):
       log_level = logging.DEBUG

    try:
        keep = config.getint('general', 'keep')
    except ConfigParser.NoOptionError:
        keep = 30

    logging.basicConfig(level=log_level, datefmt="%Y%m%d %H:%M:%S",
            format="%(asctime)s - %(levelname)s - %(message)s")

    nm = notmuch.Database()

    for server in config.get('general', 'servers').split():
        logging.info('Polling %s...' % server)
        try:
            ext = config.get(server, 'extension')
        except:
            ext = ''
        poll_server(host = config.get(server, 'host'),
                    user = config.get(server, 'user'),
                    password = config.get(server, 'password'),
                    extension = ext)

        if not (config.has_option('general', 'delete_mail') and \
                    config.getboolean('general', 'delete_mail')):
            logging.debug('Not deleting old mail.')
            return

        logging.info('Cleaning %s...' % server)
        delete_old(host = config.get(server, 'host'),
                   user = config.get(server, 'user'),
                   password = config.get(server, 'password'),
                   delay = keep)

if __name__ == '__main__':
    main()
